### ISSUE TITLE
No Dataset List available

### ISSUE THREAD

**Issue by FrauMahlzahn** [piMoll/swissgeodownloader#1]
I cannot choose datasets to download from, the list "1. Dataset" is empty. I am using QGIS 3.16.8.

**Comment by piMoll** [comment]
Hi! Thanks for your message.

This is probably because the connection to the swisstopo API is not possible. Can you check your internet connection? I could also imagine that there are network restrictions (for example if you are working on a company PC with a strict firewall).

Can you look at the messages tab (bottom right corner, speech bubble icon). There should be a tab "Swiss Geo Downloader". Are there any error messages in this tab?
